[versions]
alchemist = "42.3.26"
kotest = "5.9.1"
kotlin = "2.2.0"
mockito = "5.18.0"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-loading = { module = "it.unibo.alchemist:alchemist-loading", version.ref = "alchemist" }
apache-commons-cli = "commons-cli:commons-cli:1.9.0"
apache-commons-io = "commons-io:commons-io:2.21.0"
guava = "com.google.guava:guava:33.5.0-jre"
logback = "ch.qos.logback:logback-classic:1.5.23"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
resourceloader = "org.danilopianini:thread-inheritable-resource-loader:0.3.8"

[bundles]

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:7.0.8"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.93.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.2"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.0"
taskTree = "com.dorongold.task-tree:4.0.1"
